apiVersion: v1
kind: PersistentVolume
metadata:
  name: data01
spec:
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard