apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - env:
        - name: node.name
          value: "elasticsearch"
        - name: cluster.name
          value: "es-docker-cluster"
        - name: cluster.initial_master_nodes
          value: "elasticsearch"
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"  
        name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data01
        ports:
        - containerPort: 9200
      volumes:
      - name: data01
        persistentVolumeClaim:
          claimName: data01