apiVersion: apps/v1
kind: Deployment
metadata:
  name: kib01
  labels:
    app: kib01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kib01
  template:
    metadata:
      labels:
        app: kib01
    spec:
      containers:
      - name: kib01
        image: docker.elastic.co/kibana/kibana:7.6.2
        ports:
        - containerPort: 5601
        - env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200